import streamlit as st
st.title("My Thesis")
st.image('ML.jpg')
st.write("This website is about my research about my Graduate Thesis. Hope everything will be success!")
st.title("1. Yolo")
st.image('yolo.png')
st.write("Yolo is a deep learning model, it's application is support for Object Detection.")
st.write("Yolo Tutorial")
if st.button("Yolo"):
    st.write("https://viblo.asia/p/tim-hieu-ve-yolo-trong-bai-toan-real-time-object-detection-yMnKMdvr57P")
st.title("2. OpenCV")
st.image('opencv.jpg')
st.write("OpenCV is open source library for Image Processing and Computer Vision.")
st.write("\nHere is it's description. This page has a lots of necessary things about OpenCV functions.")
st.write("OpenCV Tutorial")
if st.button("OpenCV"):
    st.write("https://docs.opencv.org/4.x/d6/d00/tutorial_py_root.html")
st.title("3. Streamlit")
st.image('streamlit.png')
st.write("Streamlit is a python library for web development. This is is one of the fastest ways for python developer to create a website by Python Language.")
st.write("Streamlit Tutorial")
if st.button("Streamlit"):
    st.write("https://streamlitpython.com/")
st.title("4. ESP32 Cam")
st.image('ESP32 CAM.jpg')
st.write("ESP32 Cam is a MCU like ESP32 and also is a programmable camera module")
st.write("\nESP32 Cam Tutorial")
if st.button("ESP32 Cam"):
    st.write("https://randomnerdtutorials.com/esp32-cam-video-streaming-face-recognition-arduino-ide/")
st.sidebar.title("Reference")
st.sidebar.write("[Image Processing>](https://users.soict.hust.edu.vn/ductq/XLA%20Lecture.pdf)")
st.sidebar.write("[Python>](https://www.py4e.com/lessons)")
st.sidebar.write("[ESP32>](https://randomnerdtutorials.com/getting-started-with-esp32/)")
st.sidebar.write("[Streamlit official website](https://streamlit.io/)")